auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            WangPuV.com
url:              http://wangpuv.com
feed:             /atom.xml
author:
    name:         WangPuV
    twitter:      twitter.com/wangpuv
description:      "WangPuV.com"
author_info:      <a href="http://wangpuv.com">WangPuV</a>

copyright:
    - Design by <a href="http://beiyuu.com/about" title="BeiYuu" target="_blank">BeiYuu</a> &copy; 2013
